Pull Addon
docksal/addons pull request #78
Opened 2022-03-12 10:30 UTC by sean-e-dietrich

Moving from Core into it's own addon

2022-03-12 15:57 UTC, shelane requested changes
Some updated links and rewording of linking to the tools.

2022-03-12 15:57 UTC, shelane commented on pull/README.md
> +quicker to get updates to just the addon as opposed to the whole platform.
The `pull` addon was recently a core command but has been moved to an addon command.

2022-03-12 15:57 UTC, shelane commented on pull/README.md
> +is required. If access is not allowed, fallback to using the [Drush](https://docs.docksal.io/fin/fin-pull/#drupal-drush) method.
"To interact with Acquia through the Acquia CLI, ..."

Drush to Acquia only requires an SSH key. It's the Acquia CLI that requires the additional secret and key.

2022-03-12 15:57 UTC, shelane commented on pull/README.md
> +More information on working with [Docksal with Acquia Drush](https://docs.docksal.io/tools/acquia-drush).
More information on working with [Acquia CLI in Docksal](https://docs.docksal.io/tools/acquia-cli/).

2022-03-12 15:57 UTC, shelane commented on pull/README.md
> +More information on working with [Docksal with Pantheon](https://docs.docksal.io/tools/terminus).
[Pantheon in Docksal]

2022-03-12 15:57 UTC, shelane commented on pull/README.md
> +More information on working with [Docksal with Platform.sh](https://docs.docksal.io/tools/platformsh).
[Platform.sh in Docksal]

2022-03-12 15:57 UTC, shelane commented on pull/README.md
> +More information on working with [Docksal and WP-CLI](https://docs.docksal.io/tools/wp-cli).
[WP-CLI in Docksal]

2022-03-14 17:47 UTC, shelane approved these changes

2022-04-01 16:21 UTC, lmakarov approved these changes

2022-04-01 16:22 UTC, merged