Create xdebug addon
docksal/addons pull request #89
Opened 2022-08-30 19:30 UTC by froboy

A very simple addon to turn xdebug on or off.

2022-08-30 19:49 UTC, shelane submitted a review, later dismissed
Looks very similar to a custom command that I have.

2022-08-30 20:20 UTC, froboy commented
@shelane thanks. Yea... it's been hanging out for a while and I figure it'd be nice to share. I could set no option to toggle the state, but figure doing nothing is always... non-destructive.

2022-10-14 14:08 UTC, shelane commented
Please create in your PR an update to the readme file with this included in alphabetical order in the list.

2022-10-14 14:09 UTC, shelane requested changes
Readme needs update

2022-10-14 14:34 UTC, shelane approved these changes

2022-10-14 16:57 UTC, shelane requested changes
See inline comment

2022-10-14 16:57 UTC, shelane commented on xdebug/xdebug
> +        echo "Please tell me 'on' or 'off'."
Sorry, just one more nit-picky little thing. For consistency of verbiage with other commands, can you change this to:

`"Usage: fin xdebug <on|off>"`

and add `exit 1` on the next line?

2022-12-09 16:53 UTC, merged