replaces mailhog with mailpit
docksal/addons pull request #95
Opened 2024-04-02 14:58 UTC by shelane

Removing the abandoned mailhog with mailpit and updating the yaml file based on our recommended extends approach.

2024-04-02 15:35 UTC, lmakarov requested changes
`PHP_INI` and `MAILHOG_INI` are no longer relevant for `mailpit` (nor where they for `mailhog`) since this change in `docksal/cli` - https://github.com/docksal/service-cli/issues/103

@shelane Can you please update the mailpit addon to remove the unnecessary code?

2024-04-02 18:48 UTC, shelane commented
Yeah, I had removed that. The mailpit directory does not contain the ini file and the whole mailhog directory is being deleted with this request.

2024-04-03 02:01 UTC, shelane commented
Ah, I see where you mean. Fixing now.

2024-04-03 15:17 UTC, lmakarov requested changes

2024-04-03 15:17 UTC, lmakarov commented on mailpit/mailpit.post-install
> +echo -e "${green}More documentation:${NC} http://docs.docksal.io/en/master/tools/mailpit/"
```suggestion
echo -e "${green}More documentation:${NC} https://docs.docksal.io/service/other/mailpit/"
```

2024-04-03 15:17 UTC, lmakarov commented on mailpit/mailpit
> +		MAILPIT_enable
```suggestion
		mailpit_enable
```

2024-04-03 15:17 UTC, lmakarov commented on mailpit/mailpit
> +		MAILPIT_disable
```suggestion
		mailpit_disable
```

2024-04-03 15:17 UTC, lmakarov commented on mailpit/mailpit
> +MAILPIT_enable ()
```suggestion
mailpit_enable ()
```

2024-04-03 15:17 UTC, lmakarov commented on mailpit/mailpit
> +MAILPIT_disable ()
```suggestion
mailpit_disable ()
```

2024-04-03 15:19 UTC, lmakarov approved these changes

2024-04-03 15:19 UTC, merged